apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
              - /bin/sh
              - -c
            args: 
              - 'kubectl delete deploy nginx-deployment-lea1'
          restartPolicy: Never