apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxx
  template:
    metadata:
      labels:
        app: nginxx
    spec:
      containers:
      - name: nginxx
        image: public.ecr.aws/u7n6c5a4/app
        ports:
        - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service-loadbalancer
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginxx
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
